function RHS = LLE_test(x)
 
 global h sigma_X tau0 uS
 h
 sigma_X
 tau0
 uS
 
  warning('ON','MATLAB:integral:MinStepSize');

 FIa = @(t,x) (h .^ 2 .* (t - tau0) .^ 2 ./ sigma_X .^ 4 .* exp(-(t - tau0) .^ 2 ./ ...
     sigma_X .^ 2 ./ 2) .^ 2 + h ./ sigma_X .^ 2 .* exp(-(t - tau0) .^ 2 ./ ...
     sigma_X .^ 2 ./ 2) - h .* (t - tau0) .^ 2 ./ sigma_X .^ 4 .* exp(-(t - tau0) .^ 2 ./ ...
     sigma_X .^ 2 ./ 2) - x(1) .^ 2 .* exp(-(t - x(6)) .^ 2 ./ x(5) .^ 2 ./ 2) .^ 2) .* ...
     x(1) .* exp(-(t - x(6)) .^ 2 ./ x(5) .^ 2 ./ 2) .* (2 .* real(uS) .* ...
     cos(x(2) + x(3) .* (t - x(6)) + x(4) .* (t - x(6)) .^ 2) - 2 .* imag(uS) .* sin(x(2) +...
     x(3) .* (t - x(6)) + x(4) .* (t - x(6)) .^ 2)) - x(1) .^ 2 .* exp(-(t - x(6)) .^ 2 ./ ...
     x(5) .^ 2 ./ 2) .^ 2 .* (2 .* imag(uS) .^ 2 .* sin(2 .* x(2) + ...
     2 .* x(3) .* (t - x(6)) + 2 .* x(4) .* (t - x(6)) .^ 2) - ...
     2 .* real(uS) .^ 2 .* sin(2 .* x(2) + 2 .* x(3) .* (t - x(6)) + ...
     2 .* x(4) .* (t - x(6)) .^ 2) + 0.4e1 .* imag(uS) .* real(uS) .* cos(2 .* x(2) + ...
     2 .* x(3) .* (t - x(6)) + 2 .* x(4) .* (t - x(6)) .^ 2));
 
 Ia = integral(@(t)FIa(t,x),-inf,inf,'AbsTol',1e-15,'RelTol',1e-13);
 
 FA = Ia;
 RHS = [ FA; 0; 0; 0; 0; 0];
 

 
end


%     function a = FIa(t,x)
%     
%     
%  global delta h sigma_X  tau0 uS
%         a =  (h .^ 2 .* (t - tau0) .^ 2 ./ sigma_X .^ 4 .* exp(-(t - tau0) .^ 2 ./...
%      sigma_X .^ 2 ./ 2) .^ 2 + h ./ sigma_X .^ 2 .* exp(-(t - tau0) .^ 2 ./...
%      sigma_X .^ 2 ./ 2) - h .* (t - tau0) .^ 2 ./ sigma_X .^ 4 .* exp(-(t - tau0) .^ 2 ./...
%      sigma_X .^ 2 ./ 2) - x(1) .^ 2 .* exp(-(t - x(6)) .^ 2 ./ x(5) .^ 2 ./ 2) .^ 2) .*...
%      x(1) .* exp(-(t - x(6)) .^ 2 ./ x(5) .^ 2 ./ 2) .* (2 .* real(uS) .* ...
%      cos(x(2) + x(3) .* (t - x(6)) + x(4) .* (t - x(6)) .^ 2) - 2 .* imag(uS) .* sin(x(2) +...
%      x(3) .* (t - x(6)) + x(4) .* (t - x(6)) .^ 2)) - x(1) .^ 2 .* exp(-(t - x(6)) .^ 2 ./...
%      x(5) .^ 2 ./ 2) .^ 2 .* (2 .* imag(uS) .^ 2 .* sin(2 .* x(2) +...
%      2 .* x(3) .* (t - x(6)) + 2 .* x(4) .* (t - x(6)) .^ 2) -...
%      2 .* real(uS) .^ 2 .* sin(2 .* x(2) + 2 .* x(3) .* (t - x(6)) +...
%      2 .* x(4) .* (t - x(6)) .^ 2) + 0.4e1 .* imag(uS) .* real(uS) .* cos(2 .* x(2) +...
%      2 .* x(3) .* (t - x(6)) + 2 .* x(4) .* (t - x(6)) .^ 2));
%     end